import type { Match, Venue, TicketCategory, MerchandiseItem } from '@/types';
import dallasImg from '@/assets/dallas-venue.jpg';
import newyorkImg from '@/assets/newyork-venue.jpg';
import laImg from '@/assets/la-venue.jpg';
import miamiImg from '@/assets/miami-venue.jpg';
import seattleImg from '@/assets/seattle-venue.jpg';

export const VENUES: Venue[] = [
  {
    id: 'new-york',
    city: 'New York/New Jersey',
    country: 'USA',
    stadium: 'MetLife Stadium',
    capacity: 82500,
    matches: 8,
    image: newyorkImg,
    description: 'The largest NFL stadium hosts the FIFA World Cup 2026™ Final. MetLife Stadium in East Rutherford, New Jersey is one of the largest stadiums in the NFL. It will host 8 matches at FIFA World Cup 2026™, including the Final.',
    highlights: ['Hosts the Final', '8 matches total', 'Capacity 82,500', 'NFL home of Giants & Jets'],
  },
  {
    id: 'los-angeles',
    city: 'Los Angeles',
    country: 'USA',
    stadium: 'SoFi Stadium',
    capacity: 70240,
    matches: 8,
    image: laImg,
    description: "Los Angeles, the entertainment capital of the world, will host 8 matches at FIFA World Cup 2026™ including a Semi-Final. SoFi Stadium is one of the world's most modern sporting venues.",
    highlights: ['Hosts a Semi-Final', '8 matches total', 'Capacity 70,240', 'Home of the Rams & Chargers'],
  },
  {
    id: 'dallas',
    city: 'Dallas',
    country: 'USA',
    stadium: 'AT&T Stadium',
    capacity: 80000,
    matches: 9,
    image: dallasImg,
    description: 'With an impressively large youth football system, an incredible stadium, Dallas is prepared for the FIFA World Cup™. AT&T Stadium will host 9 matches including a Semi-Final match.',
    highlights: ['Hosts a Semi-Final', '9 matches total', 'Capacity 80,000', 'Home of Dallas Cowboys'],
  },
  {
    id: 'miami',
    city: 'Miami',
    country: 'USA',
    stadium: 'Hard Rock Stadium',
    capacity: 65326,
    matches: 6,
    image: miamiImg,
    description: "Miami's Hard Rock Stadium will host 6 matches at FIFA World Cup 2026™. The city is known for its vibrant culture, beautiful beaches, and passionate football fanbase.",
    highlights: ['6 matches total', 'Capacity 65,326', 'Home of Miami Dolphins', 'Near South Beach'],
  },
  {
    id: 'seattle',
    city: 'Seattle',
    country: 'USA',
    stadium: 'Lumen Field',
    capacity: 68740,
    matches: 6,
    image: seattleImg,
    description: 'Seattle is a passionate soccer city and Lumen Field will host 6 matches at FIFA World Cup 2026™. The city is home to one of the most dedicated fan bases in MLS.',
    highlights: ['6 matches total', 'Capacity 68,740', 'MLS & NFL home', 'Pacific Northwest culture'],
  },
  {
    id: 'san-francisco',
    city: 'San Francisco Bay Area',
    country: 'USA',
    stadium: "Levi's Stadium",
    capacity: 68500,
    matches: 6,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=450&fit=crop&q=80',
    description: "Levi's Stadium in Santa Clara will host 6 FIFA World Cup 2026™ matches. Silicon Valley and the Bay Area bring technological innovation to the world's biggest sporting event.",
    highlights: ['6 matches total', 'Capacity 68,500', 'Silicon Valley location', 'Home of 49ers'],
  },
  {
    id: 'boston',
    city: 'Boston',
    country: 'USA',
    stadium: 'Gillette Stadium',
    capacity: 65878,
    matches: 6,
    image: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800&h=450&fit=crop&q=80',
    description: 'Boston, one of America\'s most storied sports cities, hosts 6 FIFA World Cup 2026™ matches. Gillette Stadium in Foxborough is home to the New England Patriots.',
    highlights: ['6 matches total', 'Capacity 65,878', 'Home of Patriots', 'Rich sports heritage'],
  },
  {
    id: 'kansas-city',
    city: 'Kansas City',
    country: 'USA',
    stadium: 'Arrowhead Stadium',
    capacity: 76416,
    matches: 6,
    image: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&h=450&fit=crop&q=80',
    description: 'Arrowhead Stadium, one of the loudest stadiums in the NFL, will host 6 FIFA World Cup 2026™ matches. Kansas City is ready to welcome the world.',
    highlights: ['6 matches total', 'Capacity 76,416', 'One of NFL\'s loudest venues', 'Home of Chiefs'],
  },
  {
    id: 'houston',
    city: 'Houston',
    country: 'USA',
    stadium: 'NRG Stadium',
    capacity: 72220,
    matches: 6,
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&h=450&fit=crop&q=80',
    description: 'Houston, one of the most diverse cities in America, will host 6 FIFA World Cup 2026™ matches at NRG Stadium, a world-class facility that has hosted major events.',
    highlights: ['6 matches total', 'Capacity 72,220', 'Air-conditioned dome', 'Most diverse US city'],
  },
  {
    id: 'philadelphia',
    city: 'Philadelphia',
    country: 'USA',
    stadium: 'Lincoln Financial Field',
    capacity: 69796,
    matches: 6,
    image: 'https://images.unsplash.com/photo-1569163139394-de4e4f43e4e3?w=800&h=450&fit=crop&q=80',
    description: "Philadelphia's Lincoln Financial Field will host 6 FIFA World Cup 2026™ matches. The city of brotherly love has a passionate sports culture and deep football history.",
    highlights: ['6 matches total', 'Capacity 69,796', 'Home of Eagles', 'Historic American city'],
  },
  {
    id: 'atlanta',
    city: 'Atlanta',
    country: 'USA',
    stadium: 'Mercedes-Benz Stadium',
    capacity: 71000,
    matches: 6,
    image: 'https://images.unsplash.com/photo-1534768654272-e97681c3a2c7?w=800&h=450&fit=crop&q=80',
    description: 'Atlanta\'s Mercedes-Benz Stadium is one of the most advanced sports venues in the world, hosting 6 FIFA World Cup 2026™ matches. It hosted the 1994 World Cup and Olympics.',
    highlights: ['6 matches total', 'Capacity 71,000', 'Hosted 1994 WC & Olympics', 'State-of-the-art dome'],
  },
  {
    id: 'vancouver',
    city: 'Vancouver',
    country: 'Canada',
    stadium: 'BC Place',
    capacity: 54500,
    matches: 7,
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=450&fit=crop&q=80',
    description: 'Vancouver will host 7 FIFA World Cup 2026™ matches at BC Place, a stunning retractable-roof stadium. With beautiful mountains and ocean as backdrop, Vancouver is iconic.',
    highlights: ['7 matches total', 'Capacity 54,500', 'Retractable roof', 'Mountain & ocean views'],
  },
  {
    id: 'toronto',
    city: 'Toronto',
    country: 'Canada',
    stadium: 'BMO Field',
    capacity: 45736,
    matches: 7,
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&h=450&fit=crop&q=80',
    description: "Toronto, Canada's largest city, will host 7 FIFA World Cup 2026™ matches at BMO Field. The multicultural capital is home to one of the most diverse populations in the world.",
    highlights: ['7 matches total', 'Capacity 45,736', "Canada's largest city", 'Ultra-multicultural'],
  },
  {
    id: 'guadalajara',
    city: 'Guadalajara',
    country: 'Mexico',
    stadium: 'Estadio Akron',
    capacity: 49850,
    matches: 5,
    image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&h=450&fit=crop&q=80',
    description: "Guadalajara's Estadio Akron, home of Club Deportivo Guadalajara (Chivas), will host 5 FIFA World Cup 2026™ matches. Mexico's second largest city is a hotbed of football passion.",
    highlights: ['5 matches total', 'Capacity 49,850', 'Home of Chivas', "Mexico's football heartland"],
  },
  {
    id: 'mexico-city',
    city: 'Mexico City',
    country: 'Mexico',
    stadium: 'Estadio Azteca',
    capacity: 87523,
    matches: 5,
    image: 'https://images.unsplash.com/photo-1509339022327-1e1e25bf6a99?w=800&h=450&fit=crop&q=80',
    description: 'The iconic Estadio Azteca returns to host FIFA World Cup 2026™ matches. Mexico City will become the first city to host matches in three FIFA World Cups (1970, 1986, 2026).',
    highlights: ['5 matches total', 'Capacity 87,523', '3rd WC (1970, 1986, 2026)', 'Iconic football cathedral'],
  },
  {
    id: 'monterrey',
    city: 'Monterrey',
    country: 'Mexico',
    stadium: 'Estadio BBVA',
    capacity: 53500,
    matches: 5,
    image: 'https://images.unsplash.com/photo-1551958219-acbc338f7d0c?w=800&h=450&fit=crop&q=80',
    description: "Monterrey's modern Estadio BBVA, set against the dramatic backdrop of the Sierra Madre mountains, will host 5 FIFA World Cup 2026™ matches.",
    highlights: ['5 matches total', 'Capacity 53,500', 'Mountain backdrop', 'Modern stadium design'],
  },
];

export const TICKET_CATEGORIES: TicketCategory[] = [
  {
    id: 'cat1',
    name: 'Category 1',
    price: 220,
    currency: 'USD',
    description: 'Premium seating behind the goals or in corner sections.',
    includes: ['Match ticket', 'Official programme', 'Fan ID'],
    available: true,
    type: 'standard',
  },
  {
    id: 'cat2',
    name: 'Category 2',
    price: 165,
    currency: 'USD',
    description: 'Great viewing experience from midfield sections.',
    includes: ['Match ticket', 'Official programme', 'Fan ID'],
    available: true,
    type: 'standard',
  },
  {
    id: 'cat3',
    name: 'Category 3',
    price: 110,
    currency: 'USD',
    description: 'Affordable access to experience the world\'s greatest football event.',
    includes: ['Match ticket', 'Fan ID'],
    available: true,
    type: 'standard',
  },
  {
    id: 'hospitality-classic',
    name: 'FIFA Hospitality Classic',
    price: 890,
    currency: 'USD',
    description: 'Full hospitality experience with premium dining and match access.',
    includes: ['Premium Category 1 seat', 'Pre-match hospitality', 'Gourmet buffet', 'Open bar', 'Official gift'],
    available: true,
    type: 'hospitality',
  },
  {
    id: 'hospitality-premium',
    name: 'FIFA Hospitality Premium',
    price: 1850,
    currency: 'USD',
    description: 'The ultimate match day experience with exclusive lounge access.',
    includes: ['Best Category 1 seat', 'Exclusive lounge access', 'Fine dining', 'Premium open bar', 'Meet & greet', 'Official signed memento'],
    available: true,
    type: 'hospitality',
  },
  {
    id: 'vip-box',
    name: 'VIP Private Box',
    price: 4500,
    currency: 'USD',
    description: 'Private luxury box for 10 guests with dedicated butler service.',
    includes: ['Private 10-person box', 'Dedicated butler', 'Champagne service', 'Premium pitch-side view', 'VIP parking', 'Exclusive gifts', 'Player meet & greet'],
    available: true,
    type: 'vip',
  },
  {
    id: 'vip-pitchside',
    name: 'VIP Pitch-Side Seats',
    price: 2800,
    currency: 'USD',
    description: 'Exclusive pitch-level seating for the ultimate proximity experience.',
    includes: ['Pitch-side Category A seat', 'Dedicated concierge', 'Premium hospitality lounge', 'Champagne & fine dining', 'Match ball replica', 'Pre-match pitch walk'],
    available: true,
    type: 'vip',
  },
  {
    id: 'tour-city',
    name: 'City Experience Tour',
    price: 195,
    currency: 'USD',
    description: 'Explore the host city with an expert FIFA guide before your match.',
    includes: ['Half-day guided city tour', 'Match ticket (Cat 2)', 'Transportation', 'Local dining experience', 'FIFA Welcome gift'],
    available: true,
    type: 'tour',
  },
  {
    id: 'tour-stadium',
    name: 'Stadium Insider Tour',
    price: 145,
    currency: 'USD',
    description: 'Behind-the-scenes stadium access including dressing rooms and pitch.',
    includes: ['Stadium behind-the-scenes access', 'Dressing room visit', 'Pitch walkout tunnel', 'Expert stadium guide', 'Exclusive photos'],
    available: true,
    type: 'tour',
  },
  {
    id: 'tour-full',
    name: 'Full World Cup Experience',
    price: 680,
    currency: 'USD',
    description: 'Complete 3-day World Cup journey with premium hospitality.',
    includes: ['2x match tickets (Cat 1)', 'Hotel accommodation (2 nights)', 'City & stadium tour', 'Official fan zone access', 'VIP airport transfers', 'FIFA Official gifts'],
    available: true,
    type: 'tour',
  },
];

export const MATCHES: Match[] = [
  { id: 'm1', stage: 'Group Stage', group: 'A', date: '2026-06-11', time: '18:00', team1: 'Mexico', team1Flag: '🇲🇽', team2: 'USA', team2Flag: '🇺🇸', venue: 'Estadio Azteca', city: 'Mexico City', country: 'Mexico', matchNumber: 1 },
  { id: 'm2', stage: 'Group Stage', group: 'A', date: '2026-06-11', time: '21:00', team1: 'Canada', team1Flag: '🇨🇦', team2: 'Argentina', team2Flag: '🇦🇷', venue: 'BMO Field', city: 'Toronto', country: 'Canada', matchNumber: 2 },
  { id: 'm3', stage: 'Group Stage', group: 'B', date: '2026-06-12', time: '15:00', team1: 'Brazil', team1Flag: '🇧🇷', team2: 'Germany', team2Flag: '🇩🇪', venue: 'MetLife Stadium', city: 'New York/New Jersey', country: 'USA', matchNumber: 3 },
  { id: 'm4', stage: 'Group Stage', group: 'B', date: '2026-06-12', time: '18:00', team1: 'France', team1Flag: '🇫🇷', team2: 'Spain', team2Flag: '🇪🇸', venue: 'SoFi Stadium', city: 'Los Angeles', country: 'USA', matchNumber: 4 },
  { id: 'm5', stage: 'Group Stage', group: 'C', date: '2026-06-12', time: '21:00', team1: 'England', team1Flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', team2: 'Portugal', team2Flag: '🇵🇹', venue: 'AT&T Stadium', city: 'Dallas', country: 'USA', matchNumber: 5 },
  { id: 'm6', stage: 'Group Stage', group: 'C', date: '2026-06-13', time: '15:00', team1: 'Netherlands', team1Flag: '🇳🇱', team2: 'Italy', team2Flag: '🇮🇹', venue: 'Hard Rock Stadium', city: 'Miami', country: 'USA', matchNumber: 6 },
  { id: 'm7', stage: 'Group Stage', group: 'D', date: '2026-06-13', time: '18:00', team1: 'Japan', team1Flag: '🇯🇵', team2: 'Morocco', team2Flag: '🇲🇦', venue: 'Lumen Field', city: 'Seattle', country: 'USA', matchNumber: 7 },
  { id: 'm8', stage: 'Group Stage', group: 'D', date: '2026-06-13', time: '21:00', team1: 'Uruguay', team1Flag: '🇺🇾', team2: 'South Korea', team2Flag: '🇰🇷', venue: "Levi's Stadium", city: 'San Francisco', country: 'USA', matchNumber: 8 },
  { id: 'm9', stage: 'Group Stage', group: 'E', date: '2026-06-14', time: '15:00', team1: 'Senegal', team1Flag: '🇸🇳', team2: 'Colombia', team2Flag: '🇨🇴', venue: 'Gillette Stadium', city: 'Boston', country: 'USA', matchNumber: 9 },
  { id: 'm10', stage: 'Group Stage', group: 'E', date: '2026-06-14', time: '18:00', team1: 'Belgium', team1Flag: '🇧🇪', team2: 'Australia', team2Flag: '🇦🇺', venue: 'Arrowhead Stadium', city: 'Kansas City', country: 'USA', matchNumber: 10 },
  { id: 'm11', stage: 'Group Stage', group: 'F', date: '2026-06-14', time: '21:00', team1: 'Ecuador', team1Flag: '🇪🇨', team2: 'Croatia', team2Flag: '🇭🇷', venue: 'NRG Stadium', city: 'Houston', country: 'USA', matchNumber: 11 },
  { id: 'm12', stage: 'Group Stage', group: 'F', date: '2026-06-15', time: '15:00', team1: 'Switzerland', team1Flag: '🇨🇭', team2: 'Denmark', team2Flag: '🇩🇰', venue: 'Lincoln Financial Field', city: 'Philadelphia', country: 'USA', matchNumber: 12 },
  { id: 'm13', stage: 'Group Stage', group: 'G', date: '2026-06-15', time: '18:00', team1: 'Ghana', team1Flag: '🇬🇭', team2: 'Iran', team2Flag: '🇮🇷', venue: 'Mercedes-Benz Stadium', city: 'Atlanta', country: 'USA', matchNumber: 13 },
  { id: 'm14', stage: 'Group Stage', group: 'G', date: '2026-06-15', time: '21:00', team1: 'Saudi Arabia', team1Flag: '🇸🇦', team2: 'Poland', team2Flag: '🇵🇱', venue: 'BC Place', city: 'Vancouver', country: 'Canada', matchNumber: 14 },
  { id: 'm15', stage: 'Group Stage', group: 'H', date: '2026-06-16', time: '15:00', team1: 'Ukraine', team1Flag: '🇺🇦', team2: 'Serbia', team2Flag: '🇷🇸', venue: 'Estadio Akron', city: 'Guadalajara', country: 'Mexico', matchNumber: 15 },
  { id: 'm16', stage: 'Group Stage', group: 'H', date: '2026-06-16', time: '18:00', team1: 'Turkey', team1Flag: '🇹🇷', team2: 'Austria', team2Flag: '🇦🇹', venue: 'Estadio BBVA', city: 'Monterrey', country: 'Mexico', matchNumber: 16 },
  { id: 'qf1', stage: 'Quarter-Final', date: '2026-07-03', time: '20:00', team1: 'TBD', team1Flag: '🏳️', team2: 'TBD', team2Flag: '🏳️', venue: 'MetLife Stadium', city: 'New York/New Jersey', country: 'USA', matchNumber: 57 },
  { id: 'qf2', stage: 'Quarter-Final', date: '2026-07-04', time: '20:00', team1: 'TBD', team1Flag: '🏳️', team2: 'TBD', team2Flag: '🏳️', venue: 'AT&T Stadium', city: 'Dallas', country: 'USA', matchNumber: 58 },
  { id: 'qf3', stage: 'Quarter-Final', date: '2026-07-05', time: '20:00', team1: 'TBD', team1Flag: '🏳️', team2: 'TBD', team2Flag: '🏳️', venue: 'SoFi Stadium', city: 'Los Angeles', country: 'USA', matchNumber: 59 },
  { id: 'qf4', stage: 'Quarter-Final', date: '2026-07-05', time: '20:00', team1: 'TBD', team1Flag: '🏳️', team2: 'TBD', team2Flag: '🏳️', venue: 'NRG Stadium', city: 'Houston', country: 'USA', matchNumber: 60 },
  { id: 'sf1', stage: 'Semi-Final', date: '2026-07-10', time: '20:00', team1: 'TBD', team1Flag: '🏳️', team2: 'TBD', team2Flag: '🏳️', venue: 'AT&T Stadium', city: 'Dallas', country: 'USA', matchNumber: 61 },
  { id: 'sf2', stage: 'Semi-Final', date: '2026-07-11', time: '20:00', team1: 'TBD', team1Flag: '🏳️', team2: 'TBD', team2Flag: '🏳️', venue: 'SoFi Stadium', city: 'Los Angeles', country: 'USA', matchNumber: 62 },
  { id: 'tp', stage: 'Third Place', date: '2026-07-14', time: '18:00', team1: 'TBD', team1Flag: '🏳️', team2: 'TBD', team2Flag: '🏳️', venue: 'Hard Rock Stadium', city: 'Miami', country: 'USA', matchNumber: 63 },
  { id: 'final', stage: 'Final', date: '2026-07-19', time: '18:00', team1: 'TBD', team1Flag: '🏳️', team2: 'TBD', team2Flag: '🏳️', venue: 'MetLife Stadium', city: 'New York/New Jersey', country: 'USA', matchNumber: 64 },
];

export const MERCHANDISE: MerchandiseItem[] = [
  { id: 'merch1', name: 'FIFA World Cup 2026™ Official Ball', price: 159.99, image: 'https://images.unsplash.com/photo-1614632537197-38a17061c2bd?w=400&h=400&fit=crop&q=80', category: 'Collectibles', inStock: true, badge: 'Official Match Ball' },
  { id: 'merch2', name: 'FIFA World Cup 2026™ Official T-Shirt', price: 49.99, image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop&q=80', category: 'Apparel', sizes: ['S', 'M', 'L', 'XL', 'XXL'], inStock: true },
  { id: 'merch3', name: 'FIFA World Cup 2026™ Cap', price: 34.99, image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&h=400&fit=crop&q=80', category: 'Apparel', inStock: true },
  { id: 'merch4', name: 'FIFA World Cup 2026™ Trophy Replica', price: 299.99, image: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=400&h=400&fit=crop&q=80', category: 'Collectibles', inStock: true, badge: 'Limited Edition' },
  { id: 'merch5', name: 'USA National Team Jersey', price: 89.99, image: 'https://images.unsplash.com/photo-1576669801775-ff43c5ab079d?w=400&h=400&fit=crop&q=80', category: 'Team Gear', sizes: ['S', 'M', 'L', 'XL'], inStock: true },
  { id: 'merch6', name: 'Brazil National Team Jersey', price: 89.99, image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=400&fit=crop&q=80', category: 'Team Gear', sizes: ['S', 'M', 'L', 'XL'], inStock: true, badge: 'Best Seller' },
  { id: 'merch7', name: 'Argentina National Team Jersey', price: 89.99, image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400&h=400&fit=crop&q=80', category: 'Team Gear', sizes: ['S', 'M', 'L', 'XL'], inStock: true },
  { id: 'merch8', name: 'FIFA World Cup 2026™ Scarf', price: 29.99, image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop&q=80', category: 'Apparel', inStock: true },
  { id: 'merch9', name: 'FIFA World Cup 2026™ Pin Set', price: 24.99, image: 'https://images.unsplash.com/photo-1612776572997-76cc42e058c3?w=400&h=400&fit=crop&q=80', category: 'Collectibles', inStock: true },
  { id: 'merch10', name: 'FIFA World Cup 2026™ Backpack', price: 79.99, image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&q=80', category: 'Accessories', inStock: true },
  { id: 'merch11', name: 'France National Team Jersey', price: 89.99, image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&q=80', category: 'Team Gear', sizes: ['S', 'M', 'L', 'XL'], inStock: true },
  { id: 'merch12', name: 'FIFA World Cup 2026™ Keychain', price: 14.99, image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&q=80', category: 'Collectibles', inStock: true },
];

export const TEAMS = [
  { name: 'Argentina', flag: '🇦🇷', group: 'A', confederation: 'CONMEBOL' },
  { name: 'Brazil', flag: '🇧🇷', group: 'B', confederation: 'CONMEBOL' },
  { name: 'France', flag: '🇫🇷', group: 'B', confederation: 'UEFA' },
  { name: 'Spain', flag: '🇪🇸', group: 'B', confederation: 'UEFA' },
  { name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'C', confederation: 'UEFA' },
  { name: 'Germany', flag: '🇩🇪', group: 'B', confederation: 'UEFA' },
  { name: 'Portugal', flag: '🇵🇹', group: 'C', confederation: 'UEFA' },
  { name: 'Netherlands', flag: '🇳🇱', group: 'C', confederation: 'UEFA' },
  { name: 'Italy', flag: '🇮🇹', group: 'C', confederation: 'UEFA' },
  { name: 'Belgium', flag: '🇧🇪', group: 'E', confederation: 'UEFA' },
  { name: 'USA', flag: '🇺🇸', group: 'A', confederation: 'CONCACAF' },
  { name: 'Mexico', flag: '🇲🇽', group: 'A', confederation: 'CONCACAF' },
  { name: 'Canada', flag: '🇨🇦', group: 'A', confederation: 'CONCACAF' },
  { name: 'Japan', flag: '🇯🇵', group: 'D', confederation: 'AFC' },
  { name: 'South Korea', flag: '🇰🇷', group: 'D', confederation: 'AFC' },
  { name: 'Saudi Arabia', flag: '🇸🇦', group: 'G', confederation: 'AFC' },
  { name: 'Morocco', flag: '🇲🇦', group: 'D', confederation: 'CAF' },
  { name: 'Senegal', flag: '🇸🇳', group: 'E', confederation: 'CAF' },
  { name: 'Ghana', flag: '🇬🇭', group: 'G', confederation: 'CAF' },
  { name: 'Uruguay', flag: '🇺🇾', group: 'D', confederation: 'CONMEBOL' },
  { name: 'Colombia', flag: '🇨🇴', group: 'E', confederation: 'CONMEBOL' },
  { name: 'Ecuador', flag: '🇪🇨', group: 'F', confederation: 'CONMEBOL' },
  { name: 'Croatia', flag: '🇭🇷', group: 'F', confederation: 'UEFA' },
  { name: 'Switzerland', flag: '🇨🇭', group: 'F', confederation: 'UEFA' },
  { name: 'Denmark', flag: '🇩🇰', group: 'F', confederation: 'UEFA' },
  { name: 'Turkey', flag: '🇹🇷', group: 'H', confederation: 'UEFA' },
  { name: 'Austria', flag: '🇦🇹', group: 'H', confederation: 'UEFA' },
  { name: 'Ukraine', flag: '🇺🇦', group: 'H', confederation: 'UEFA' },
  { name: 'Serbia', flag: '🇷🇸', group: 'H', confederation: 'UEFA' },
  { name: 'Australia', flag: '🇦🇺', group: 'E', confederation: 'AFC' },
  { name: 'Iran', flag: '🇮🇷', group: 'G', confederation: 'AFC' },
  { name: 'Poland', flag: '🇵🇱', group: 'G', confederation: 'UEFA' },
  { name: 'Ukraine', flag: '🇺🇦', group: 'H', confederation: 'UEFA' },
  { name: 'China PR', flag: '🇨🇳', group: 'I', confederation: 'AFC' },
  { name: 'Indonesia', flag: '🇮🇩', group: 'I', confederation: 'AFC' },
  { name: 'New Zealand', flag: '🇳🇿', group: 'I', confederation: 'OFC' },
  { name: 'Egypt', flag: '🇪🇬', group: 'J', confederation: 'CAF' },
  { name: 'Nigeria', flag: '🇳🇬', group: 'J', confederation: 'CAF' },
  { name: 'Cameroon', flag: '🇨🇲', group: 'J', confederation: 'CAF' },
  { name: 'Chile', flag: '🇨🇱', group: 'K', confederation: 'CONMEBOL' },
  { name: 'Paraguay', flag: '🇵🇾', group: 'K', confederation: 'CONMEBOL' },
  { name: 'Venezuela', flag: '🇻🇪', group: 'K', confederation: 'CONMEBOL' },
  { name: 'Costa Rica', flag: '🇨🇷', group: 'L', confederation: 'CONCACAF' },
  { name: 'Panama', flag: '🇵🇦', group: 'L', confederation: 'CONCACAF' },
  { name: 'Honduras', flag: '🇭🇳', group: 'L', confederation: 'CONCACAF' },
  { name: 'Greece', flag: '🇬🇷', group: 'M', confederation: 'UEFA' },
  { name: 'Czech Republic', flag: '🇨🇿', group: 'M', confederation: 'UEFA' },
  { name: 'Slovakia', flag: '🇸🇰', group: 'M', confederation: 'UEFA' },
];
